### ISSUE TITLE
OpenStack SDK not support server creation with param availability_zone

### ISSUE THREAD

**Issue by lk668** [Cindia-blue/multivimdriver-vmware-vio#49]
When I create a server and set the availability_zone=nova attribute, I get the following error.
{u'name': u'test-lk', u'imageRef': u'906284d4-bdf1-4bcf-bbb2-97d143fd1268', u'flavorRef': u'2', u'user_data': u'eHh4\n', u'OS-EXT-AZ:availability_zone': u'nova', u'networks': [{u'port': u'749c06aa-5cad-41d4-8c38-771c41e730fb'}], u'security_groups': [{u'name': u'default'}]}. Additional properties are not allowed (u'OS-EXT-AZ:availability_zone' was unexpected)

But when I set  availability_zone="", it works normally.

It is a bug for OpenStack SDK. The related link is the following.
https://bugs.launchpad.net/python-openstacksdk/+bug/1671073

**Comment by lynic** [comment]
There's a patch pending to fix it in sdk. https://review.openstack.org/#/c/444933/

**Comment by Cindia-blue** [comment]
The fix will be included by next versioned SDK.
